main_app/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('blogs/', views.blogs_index, name='index'),
    path('blogs/<int:blog_id>/', views.blogs_detail, name='detail'),
    path('blogs/create/', views.BlogCreate.as_view(), name='blogs_create'),
    path('blogs/<int:pk>/update/', views.BlogUpdate.as_view(), name='blogs_update'),
    path('blogs/<int:pk>/delete/', views.BlogDelete.as_view(), name='blogs_delete'),
    path('blogs/<int:blog_id>/add_food/', views.add_food, name='add_food'),
    path('blogs/<int:blog_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

my_project4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from dataclasses import field
from email.policy import default
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
REVIEWS = (
    ('N', 'Never again'),
    ('W', 'Would go back'),
)

class Blog(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'blog_id': self.id})
    



class Food(models.Model):
    date = models.DateField('Date')
    review = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=REVIEWS,
        # set the default value for review to be 'N'
        default=REVIEWS[0][0]
    )

    # Create a blog_id FK
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_review_display()} on {self.date}"

    

class Photo(models.Model):
    url = models.CharField(max_length=200)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for blog_id: {self.blog_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Food

class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = ['date', 'review']

main_app/views.py
from distutils import extension
from multiprocessing import context
from re import template
from wsgiref import validate
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Blog, Photo
from .forms import FoodForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3

# Create your views here.

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'explor-avatar-31'


def home(request):
    
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')
def blogs_index(request):
    blogs = Blog.objects.filter(user=request.user)
    return render(request, 'blogs/index.html', {'blogs': blogs})


@login_required
def blogs_detail(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    # FoodForm to be rendered in the template
    food_form = FoodForm()
    return render(request, 'blogs/detail.html', {
        # including the cat and food_form in the context
        'blog': blog, 'food_form': food_form})


@login_required
def add_food(request, blog_id):
    # create the ModelForm using the data in request.POST
    form = FoodForm(request.POST)
    # validate the form
    if form.is_valid():
        # dont save the form to the db until it has blog_id assigned
        new_food = form.save(commit=False)
        new_food.blog_id = blog_id
        new_food.save()
    return redirect('detail', blog_id=blog_id)


@login_required
def add_photo(request, blog_id):
    # photo_file will be the 'name' attribute on the <input type='file'>
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # needs a unique 'key' for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
                         photo_file.name[photo_file.name.rfind('.'):]
        # in case something is wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # assign to blog_id or blog (if you have a blog obj)
            photo = Photo(url=url, blog_id=blog_id)
            photo.save()
        except Exception as error:
            print('Error uploading  photo: ', error)
            return redirect('detail', blog_id=blog_id)
    return redirect('detail', blog_id=blog_id)


class BlogCreate(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('name', 'location', 'description')
    success_url = '/blogs/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class BlogUpdate(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ['location', 'description']


class BlogDelete(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = '/blogs/'


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again!'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<style>
  body {
      background-image: url('https://images.unsplash.com/photo-1540597458480-43a890696f68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1501&q=80');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
  }

  p {
    font-size: 1.6em;
    color: black;
    letter-spacing: 1px;
    text-align: center;
  }
  .p-tag {
    background-color: lightgrey;
  }
</style>
  <body>

    <h1>About the Explor</h1>
    <hr />
    <div class='p-tag'>
    <p> Explor is an app that provides an online canvas to upload your favorite trips. Provide as much detail about your trip we want to know about some of the amazing and beautiful places you have visited!!!</p>
    </div>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Explor</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    /> 
        
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo"> Explor</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'index' %}">Blog</a></li>
            <li><a href="{% url 'blogs_create' %}">Post a Blog</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, © 2022 Anasemos Kassahun 
      </div>
    </footer>
  </body>
</html>

main_app/templates/blogs/detail.html
{% extends 'base.html' %} {% block content %}
<style>
  body{
    background-color: #eceff1;
  }
</style>
<h1>Blog Details</h1>

<div class="row">
    {% for photo in blog.photo_set.all %}
          <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
          <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}

        <form action="{% url 'add_photo' blog.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file" />
        <br /><br />
        <input type="submit" class="btn" value="Upload Photo" />
      </form>
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ blog.name }}</span>
        <p>Location: {{ blog.location }}</p>
        <p>Description: {{ blog.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'blogs_update' blog.id %}">Edit</a>
        <a href="{% url 'blogs_delete' blog.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_food' blog.id %}" method="post">
        {% csrf_token %} {{ food_form.as_p }}
        <input type="submit" class="btn" value="Add Review" />
      </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Review</th>
        </tr>
      </thead>
      <tbody>
        {% for food in blog.food_set.all %}
        <tr>
          <td>{{food.date}}</td>
          <td>{{food.get_review_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
    <script>
        var dateEl = document.getElementById('id_date');
        M.Datepicker.init(dateEl, {
          format: 'yyyy-mm-dd',
          defaultDate: new Date(),
          setDefaultDate: true,
          autoClose: true
        });
        var selectEl = document.getElementById('id_review');
        M.FormSelect.init(selectEl);
    </script>
{% endblock %}

main_app/templates/blogs/index.html
{% extends 'base.html' %} {% block content %}
<style>
  body {
    background-image: url('https://images.unsplash.com/photo-1488646953014-85cb44e25828?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1035&q=80');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
}

 a {
 color: black;
}


.card .card-content {
  background-color: #ce93d8;
}
</style>

<h1>Blogs</h1>

{% for blog in blogs %}
<a href="{% url 'detail' blog.id %}">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ blog.name }}</span>
    <p>Location: {{ blog.location }}</p>
    <p>Description: {{ blog.description }}</p>
  </div>
</a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<style>
     body {
        {% comment %} background-image: url('https://images.unsplash.com/photo-1583212292454-1fe6229603b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover; {% endcomment %}
        background-color: lightgrey;
    } 
    h1 {
        text-align: center;
        color: black;
    }

    .home-info {
        text-align: center;
        font-size: 40px;
        color: black;
    }
</style>
    <h1>Welcome to Explor</h1>
    <hr />
    <p class='home-info'>Sign up to get started, or click About for more info</p>
{% endblock %}

main_app/templates/main_app/blog_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Blog</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' blog.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/blog_form.html
{% extends 'base.html' %} {% block content %}
<style>
    body {
      background-color: lightgray;

      
    }

</style>
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}